---
- hosts: ansible-server

  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/k8s-lab

  - name: create tag to image
    command: docker tag simple-devops-image vikas24775/vikas-cicd

  - name: push image on to dockerhub
    command: docker push vikas24775/vikas-cicd

  - name: remove docker images form ansible server
    command: docker rmi simple-devops-image:latest vikas24774/vikas-cicd
    ignore_errors: yes
